version:
  name: velociraptor
  version: 0.75.1
  commit: 46ff090b9
  build_time: "2025-09-03T16:01:20Z"
  compiler: go1.23.2
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://localhost:8008/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQb9n4ezA3lQDeuKM6VMgTSzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwOTMwMTIyMDQ0WhcNMzUw
    OTI4MTIyMDQ0WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEJ8EaaPKlc3j4ExgbXQ0DCSvmSJQuyFBa
    +kBIuIURnyFeNDtKgqPMKgsVarWJwa7pN4scbUUqT2w1qFcHJYe26hTw02wZWdR8
    7QA7b8Ivx0MyoKUOYLmTTjmSWKhI7XzWCSl8BbOlI1L6v0iR/vcltUBTWkuLCNwF
    VkSGwQNkx3PV5q1fT6I+a0YUcc2WeAay+XRRQ6hbTAMek+iEvldGuIWJvlr4DYGj
    30VkCqGQ+PKsxAc30vGQJ6tjA0tLcQvAJcpMWTCCC8iZeHud2MgPN5L/oFW9Ys8W
    fo4k2KeVZhkvIYLiiAhPEj8QblXQD6q1JNWa+RSEVlFBQSI6nj83AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs/5dqu+JzT1l6zJ/yFplVcYFC
    kTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAA5aK0MiDw2zkHj0LW7msiC8OzDUfxFmL547vY7r1rqOV
    AqSblj0NnC8mkhNjXBdF1yRXjUEfkplm8XIASOSD3oWkp9UiBrrW3JdbQyqDhM/w
    l7JyIxgtZD7Q3LCPllrFwDpwCBiCun+bTAkqz1VEGCHJiasOBdDC3ySFjcnyULau
    Fq2P8fC+FDm4aTSQpYSaXV39lRcGykNcmblau5jnGKB5doG7PXrmG8fpOSXQB9P3
    WfTAec7SEESmVuINnBMYyDmMNicMQo4c3amKXcWH/Tay5FejWOYir6FgGY5Wzo5b
    hogT6u5/1oe0RFlWEIbXPDIR43Uv5LThaq+u7eQ0Hg==
    -----END CERTIFICATE-----
  nonce: AHCF3XPUwT0=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:01:20Z"
    compiler: go1.23.2
    system: linux
    architecture: amd64
  server_version:
    version: 0.75.1
    commit: 46ff090b9
    build_time: "2025-09-03T16:01:20Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
